server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/box
    username: postgres
    password: Wkm8oN8t
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true